image: python:3.9

stages:
  - test

test:
  stage: test
  before_script:
    # Update package lists and install basic utilities first
    - apt-get update -y
    - echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free" | tee -a /etc/apt/sources.list
    - apt-get update -y
    # Install required packages
    - apt-get install -y --no-install-recommends \
        curl \
        gnupg \
        lsb-release \
        apt-transport-https \
        ca-certificates
  script:
    # Run the tests
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests
    - xvfb-run --auto-servernum robot tests/
  artifacts:
    paths:
      - results/
    expire_in: 1 week
