stages:
  - test

variables:
  CHROME_BIN: "/usr/bin/google-chrome"
  CHROME_LOG_FILE: "/tmp/chrome_debug.log"
  HEADLESS: "true"
  REMOTE_DEBUGGING_PORT: "9222"
  CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --disable-software-rasterizer"

test:
  stage: test
  image: python:3.9
  before_script:
    - sysctl -w vm.max_map_count=262144
    - sysctl -w fs.file-max=1000000
    - apt-get update
    - apt-get install -y wget gnupg xvfb openssl  # Install openssl for random string generation
    - apt-get install -y libxss1 libappindicator3-1 fonts-liberation libnss3 libgdk-pixbuf2.0-0 libnspr4 xdg-utils libgbm-dev
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y google-chrome-beta  # Try the beta version of Chrome
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests
    - pip install chromedriver-autoinstaller  # Install the package
    - python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"  # Install the correct chromedriver

    # Version check for Google Chrome
    - google-chrome --version

  script:
    # Kill any remaining Chrome or Chromedriver processes
    - pkill -9 -f chrome || true
    - pkill -9 -f chromedriver || true
    - killall -9 chrome || true  # Make sure no chrome processes are left
    - killall -9 chromedriver || true  # Make sure no chromedriver processes are left
    - sleep 5  # Wait for processes to terminate completely

    # Clean up any existing user data directories and lock files
    - rm -rf /tmp/chrome_user_data_*
    - rm -f /tmp/chrome_user_data_*/.lock || true
    - sleep 10  # Extra time to ensure the directories are cleared

    # Verify no lingering Chrome or Chromedriver processes
    - ps aux | grep chrome
    - ps aux | grep chromedriver

    # Check if any directories remain after cleanup
    - ls /tmp/chrome_user_data_* || true

    # Create a unique user data directory
    - export UNIQUE_USER_DATA_DIR="/tmp/chrome_user_data_$(date +%s)_$(openssl rand -hex 6)"
    - mkdir -p $UNIQUE_USER_DATA_DIR

    # Set Chrome options with the new user data directory
    - export CHROME_OPTIONS="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --disable-software-rasterizer --user-data-dir=$UNIQUE_USER_DATA_DIR"

    # Print the user data directory for debugging
    - "echo Using User Data Directory: $UNIQUE_USER_DATA_DIR"

    # Run tests with xvfb-run
    - xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" robot --outputdir results --variable CHROME_BIN:/usr/bin/google-chrome --variable CHROME_OPTIONS:"$CHROME_OPTIONS" --variable HEADLESS:true --variable DISABLE_SANDBOX:true --variable DISABLE_DEV_SHM_USAGE:true tests/

  artifacts:
    paths:
      - results/
    expire_in: 1 week
