image: ubuntu:20.04

stages:
  - test

variables:
  DISPLAY: ":99"
  SELENIUM_ARGUMENTS: "--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 --disable-software-rasterizer"

before_script:
  # Update and install system dependencies
  - apt-get update -y
  - apt-get install -y wget curl unzip python3 python3-pip libnss3 libgconf-2-4 libfontconfig1 xvfb dbus-x11 gnupg lsof apt-utils software-properties-common

  # Install Google Chrome
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux-keyring.gpg
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
  - apt-get update -y && apt-get install -y google-chrome-stable

  # Verify Google Chrome installation
  - google-chrome --version || echo "Google Chrome failed to start"

  # Install ChromeDriver
  - CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
  - wget -q https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/local/bin/
  - chmod +x /usr/local/bin/chromedriver
  - chromedriver --version || echo "Chromedriver not installed correctly"

  # Install Python dependencies
  - pip3 install robotframework robotframework-seleniumlibrary selenium

  # Set environment variables
  - export DISPLAY=$DISPLAY
  - export CHROME_BIN=/usr/bin/google-chrome
  - export CHROME_DRIVER=/usr/local/bin/chromedriver

  # Start XVFB
  - Xvfb $DISPLAY -screen 0 1280x1024x24 &
  - sleep 2

  # Start DBus
  - dbus-uuidgen > /etc/machine-id
  - service dbus start

  # Launch Chrome in headless mode
  - |
    for i in {1..3}; do
      google-chrome --headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 about:blank &
      sleep 10
      lsof -i :9222 && break || echo "Retrying Chrome launch..."
    done

test:
  stage: test
  script:
    # Run Robot Framework tests
    - robot --outputdir results --variable BROWSER:Chrome --variable SELENIUM_ARGUMENTS:"$SELENIUM_ARGUMENTS" tests/
  artifacts:
    paths:
      - results/*
