image: python:3.9-slim

stages:
  - test

variables:
  DISPLAY: ":99"
  BROWSER: "Chrome"
  SELENIUM_ARGUMENTS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0"
  CHROME_BIN: "/usr/bin/google-chrome"
  CHROME_DRIVER: "/usr/local/bin/chromedriver"
  XVFB: ":99 -screen 0 1280x1024x24"

before_script:
  # Install dependencies
  - apt-get update -y
  - apt-get install -y wget curl unzip libnss3 libgconf-2-4 libfontconfig1
  - apt-get install -y chromium chromium-driver
  - apt-get install -y xvfb
  - apt-get install -y dbus-x11

  # Start Xvfb
  - Xvfb $DISPLAY -screen 0 1280x1024x24 &
  - export DISPLAY=$DISPLAY

  # Start Google Chrome in headless mode
  - google-chrome --headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 about:blank &
  - sleep 5

  # Verify if Chrome started
  - lsof -i :9222 || echo "Chrome did not start correctly"

  # Check Chrome and ChromeDriver versions
  - google-chrome --version
  - chromedriver --version || echo "Chromedriver not installed correctly"

test:
  stage: test
  script:
    - robot --outputdir results --variable BROWSER:Chrome --variable SELENIUM_ARGUMENTS:"$SELENIUM_ARGUMENTS" tests/
  artifacts:
    paths:
      - results/*
