stages:
  - test

before_script:
  # Update package list and install necessary dependencies
  - apt-get update -y
  - apt-get install -y --no-install-recommends \
      curl \
      gnupg \
      lsb-release \
      apt-transport-https \
      ca-certificates \
      python3 \
      python3-pip \
      python3-setuptools \
      python3-dev \
      build-essential
  # Install Python dependencies
  - pip3 install --upgrade pip
  - pip3 install robotframework
  - pip3 install robotframework-seleniumlibrary
  - pip3 install robotframework-jsonlibrary
  - pip3 install robotframework-requests

test:
  stage: test
  when: manual
  script:
    # Run Robot Framework tests
    - xvfb-run --auto-servernum robot tests/
  artifacts:
    paths:
      - results/
    expire_in: 1 week
