image: python:3.9-slim

stages:
  - test

test:
  stage: test
  before_script:
    # Install necessary packages
    - apt-get update
    - apt-get install -y \
        wget \
        gnupg \
        curl \
        unzip \
        xvfb \
    # Install Robot Framework and its dependencies
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests

  script:
    # Run the tests using Xvfb for a virtual display
    - xvfb-run --auto-servernum robot tests/

  artifacts:
    paths:
      - results/
    expire_in: 1 week
