stages:
  - test

variables:
  CHROME_BIN: "/usr/bin/google-chrome"
  CHROME_LOG_FILE: "/tmp/chrome_debug.log"
  HEADLESS: "true"

test:
  stage: test
  image: python:3.9
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg xvfb
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y google-chrome-stable
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests
    - pip install chromedriver-autoinstaller
  script:
    - xvfb-run --auto-servernum robot --outputdir results --variable CHROME_BIN:/usr/bin/google-chrome --variable HEADLESS:true tests/
  artifacts:
    paths:
      - results/
    expire_in: 1 week
