image: python:3.9

stages:
  - test

test:
  stage: test
  when: manual  # This allows manual triggering of the job
  before_script:
    # Update and install dependencies
    - apt-get update -y
    - apt-get install -y --no-install-recommends \
        libxss1 \
        libappindicator3-1 \
        libindicator7 \
        fonts-liberation \
        libnss3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        xdg-utils \
        libgbm-dev \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libxcomposite1 \
        libxrandr2 \
        libxi6 \
        libxtst6 \
        libnss3-dev \
        libcurl4 \
        google-chrome-stable
    # Install Robot Framework and its dependencies
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests

  script:
    # Run the tests using Xvfb for a virtual display
    - xvfb-run --auto-servernum robot tests/

  artifacts:
    paths:
      - results/
    expire_in: 1 week
