stages:
  - test

test:
  stage: test
  image: python:3.9-slim
  before_script:
    # Install dependencies
    - apt-get update
    - apt-get install -y wget gnupg curl unzip
    - apt-get install -y google-chrome-stable
    - apt-get install -y \
        libxss1 \
        libappindicator3-1 \
        libindicator7 \
        fonts-liberation \
        libnss3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        xdg-utils \
        libgbm-dev \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libxcomposite1 \
        libxrandr2 \
        libxi6 \
        libxtst6 \
        libnss3-dev \
        libcurl4
    - apt-get install -y xvfb
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests
    - pip install chromedriver-autoinstaller

  script:
    # Run the tests in Headless mode using xvfb
    - xvfb-run --auto-servernum robot --outputdir results --variable CHROME_BIN:/usr/bin/google-chrome --variable HEADLESS:true --variable DISABLE_SANDBOX:true --variable REMOTE_DEBUGGING_PORT:9222 --variable DISABLE_DEV_SHM_USAGE:true --variable DISABLE_GPU:true --variable DISABLE_SOFTWARE_RASTERIZER:true tests/

  artifacts:
    paths:
      - results/
    expire_in: 1 week
