stages:
  - test

variables:
  CHROME_BIN: "/usr/bin/google-chrome"
  CHROME_LOG_FILE: "/tmp/chrome_debug.log"
  HEADLESS: "true"
  REMOTE_DEBUGGING_PORT: "9222"
  CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --disable-software-rasterizer"

test:
  stage: test
  image: python:3.9
  before_script:
    - sysctl -w vm.max_map_count=262144
    - sysctl -w fs.file-max=1000000
    - apt-get update
    - apt-get install -y wget gnupg xvfb
    - apt-get install -y libxss1 libappindicator3-1 fonts-liberation libnss3 libgdk-pixbuf2.0-0 libnspr4 xdg-utils libgbm-dev
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y google-chrome-beta  # Try the beta version of Chrome
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install robotframework-jsonlibrary
    - pip install robotframework-requests
    - pip install chromedriver-autoinstaller  # Install the package
    - python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"  # Install the correct chromedriver
    - google-chrome --version

  script:
    - pkill -9 chrome || true
    - export DISPLAY=:99
    - nohup Xvfb :99 -screen 0 1280x1024x24 &
    - sleep 5  # Wait for Xvfb to start
    - ps aux | grep Xvfb]
    - export UNIQUE_USER_DATA_DIR="/tmp/chrome_user_data_$(date +%s)"  # Generate unique directory for each run
    - export CHROME_OPTIONS="$CHROME_OPTIONS --user-data-dir=${UNIQUE_USER_DATA_DIR}"  # Append unique user data dir to CHROME_OPTIONS
    - xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" robot --outputdir results --variable CHROME_BIN:/usr/bin/google-chrome --variable HEADLESS:true --variable DISABLE_SANDBOX:true --variable DISABLE_DEV_SHM_USAGE:true --variable REMOTE_DEBUGGING_PORT:9222 --variable CHROME_OPTIONS:"$CHROME_OPTIONS" tests/

  artifacts:
    paths:
      - results/
    expire_in: 1 week
