image: python:3.9-slim

stages:
  - test

variables:
  DISPLAY: ":99"
  BROWSER: "Chrome"
  SELENIUM_ARGUMENTS: "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0"
  CHROME_BIN: "/usr/bin/google-chrome"
  CHROME_DRIVER: "/usr/local/bin/chromedriver"
  XVFB: ":99 -screen 0 1280x1024x24"

before_script:
  # Install dependencies
  - apt-get update -y
  - apt-get install -y wget curl unzip libnss3 libgconf-2-4 libfontconfig1
  - apt-get install -y chromium chromium-driver
  - apt-get install -y xvfb
  - apt-get install -y dbus-x11
  - apt-get install -y lsof
  - apt-get install -y gnupg
  - apt-get install -y python3-pip

  # Install Robot Framework and SeleniumLibrary
  - pip3 install robotframework
  - pip3 install robotframework-seleniumlibrary

  # Install Google Chrome if it's not already installed
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
  - apt-get update -y
  - apt-get install -y google-chrome-stable

  # Start Xvfb
  - Xvfb $DISPLAY -screen 0 1280x1024x24 &
  - sleep 2  # Allow Xvfb to start

  # Set DISPLAY environment variable
  - export DISPLAY=$DISPLAY
  - export CHROME_BIN=/usr/bin/google-chrome
  - export CHROME_DRIVER=/usr/local/bin/chromedriver

  # Start Google Chrome in headless mode
  - google-chrome --headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 about:blank &

  # Wait for Chrome to start
  - sleep 10

  # Verify if Chrome started
  - lsof -i :9222 || echo "Chrome did not start correctly"

  # Check Chrome and ChromeDriver versions
  - google-chrome --version || echo "Google Chrome failed to start"
  - chromedriver --version || echo "Chromedriver not installed correctly"

test:
  stage: test
  script:
    - robot --outputdir results --variable BROWSER:Chrome --variable SELENIUM_ARGUMENTS:"$SELENIUM_ARGUMENTS" tests/
  artifacts:
    paths:
      - results/*
