stages:
  - test

test:
  stage: test
  image: python:3.9
  before_script:
    - apt-get update -y
    - apt-get install -y wget gnupg curl xvfb fonts-liberation libnss3 libgdk-pixbuf2.0-0 libnspr4 xdg-utils libgbm-dev libasound2
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - apt-get update -y
    - apt-get install -y google-chrome-stable
    - pip install --upgrade pip
    - pip install robotframework robotframework-seleniumlibrary robotframework-jsonlibrary robotframework-requests chromedriver-autoinstaller
  script:
    - xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" robot --outputdir results tests/
  artifacts:
    paths:
      - results/
    expire_in: 1 week
