image: python:3.9-slim

stages:
  - test

variables:
  DISPLAY: ":99"
  SELENIUM_ARGUMENTS: "--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 --disable-software-rasterizer --disable-extensions --disable-background-networking --disable-default-apps --disable-popup-blocking --disable-sync --disable-translate --metrics-recording-only --safebrowsing-disable-auto-update"

before_script:
  - apt-get update -y
  - apt-get install -y wget curl unzip libnss3 libgconf-2-4 libfontconfig1
  - apt-get install -y chromium chromium-driver xvfb dbus-x11 lsof gnupg python3-pip
  - pip install --upgrade pip
  - pip3 install robotframework robotframework-seleniumlibrary
  - mount -o remount,size=2G /dev/shm
  - Xvfb $DISPLAY -screen 0 1280x1024x24 &
  - sleep 2
  - export DISPLAY=$DISPLAY
  - export CHROME_BIN=/usr/bin/google-chrome
  - export CHROME_DRIVER=/usr/local/bin/chromedriver
  - dbus-uuidgen > /etc/machine-id
  - service dbus start
  - |
    for i in {1..3}; do
      google-chrome --headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 about:blank &
      sleep 10
      lsof -i :9222 && break || echo "Retrying Chrome launch..."
    done
  - google-chrome --version || echo "Google Chrome failed to start"
  - chromedriver --version || echo "Chromedriver not installed correctly"

test:
  stage: test
  script:
    - robot --outputdir results --variable BROWSER:Chrome --variable SELENIUM_ARGUMENTS:"$SELENIUM_ARGUMENTS" tests/
  artifacts:
    paths:
      - results/*
