image: ultimatedogg/docker-robot-framework

stages:
  - test

test_job:
  stage: test
  script:
    - apt-get update && apt-get install -y wget unzip
    - pip install -r requirements.txt
    - mkdir -p results
    - robot --outputdir results/ tests/
  artifacts:
    paths:
      - results/**