image: ultimatedogg/docker-robot-framework

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y wget unzipnsure compatible versions
          - pip install -r requirements.txt
          - mkdir -p results
          - robot --outputdir results/ tests/
        artifacts:
          - results/**