image: robotframework/robot-framework-python:latest

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          - pip install --upgrade pip  # Ensure pip is up to date
          - mkdir -p results  # Create results directory
          - robot --outputdir results/ tests/  # Run the tests
        artifacts:
          - results/**
