image: python:3.9

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y wget unzip \
            chromium-driver \
            chromium \
            libgdk-pixbuf2.0-0 \
            libxss1 \
            libappindicator3-1 \
            libasound2 \
            fonts-liberation \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libgbm1
          - pip install --upgrade pip  # Ensure pip is up to date
          - pip install -r tests/requirements.txt  # Install dependencies (if you have a requirements.txt)
          - mkdir -p results  # Create results directory
          - robot --outputdir results/ tests/  # Run the tests
        artifacts:
          - results/**
