image: ultimatedogg/docker-robot-framework

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          # Update package list and install necessary utilities (wget, unzip)
          - apt-get update && apt-get install -y wget unzip

          # Install Python dependencies from the requirements.txt file
          - pip install -r tests/requirements.txt

          # Create a directory for storing test results
          - mkdir -p results

          # Run Robot Framework tests and save the results in the 'results' directory
          - robot --outputdir results/ tests/

        artifacts:
          # Store all files in the 'results' directory as artifacts
          - results/**
