image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          # Update and install required dependencies
          - apt-get update && apt-get install -y wget unzip python3-venv python3-pip

          # Create a virtual environment
          - python3 -m venv venv

          # Activate the virtual environment
          - source venv/bin/activate

          # Upgrade pip within the virtual environment
          - pip install --upgrade pip

          # Install dependencies from the requirements file
          - pip install -r tests/requirements.txt  # Use the provided path for requirements.txt

          # Create results directory
          - mkdir -p results

          # Run Robot Framework tests
          - robot --outputdir results/ tests/
        artifacts:
          - results/**
