image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          # Update and install required dependencies
          - apt-get update && apt-get install -y wget unzip

          # Install Python dependencies
          - apt-get install -y python3 python3-pip
          - pip install --upgrade pip
          - pip install -r tests/requirements.txt  # Use the provided path for requirements.txt

          # Create results directory
          - mkdir -p results

          # Run Robot Framework tests
          - robot --outputdir results/ tests/
        artifacts:
          - results/**
