image: selenium/standalone-chrome:latest

pipelines:
  default:
    - step:
        name: Run Robot Framework Tests
        caches:
          - pip
        script:
          # Install sudo and necessary packages to create virtual environment
          - apt-get update && apt-get install -y sudo python3.12-venv python3-pip
          # Install dependencies and set up virtual environment
          - sudo python3 -m venv venv
          - source venv/bin/activate  # Activate the virtual environment
          - pip install --upgrade pip
          - pip install -r tests/requirements.txt
          - mkdir -p results
          - robot --outputdir results/ tests/
        artifacts:
          - results/**
